# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1

[pt-br]
languageName = "Portugues Brasil"
languagedirection = "ltr"
title = "Exemplo Site"
weight = 1
