# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/raphanogueira"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/raphanogueira/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/_rapha.nogueira"

[[social.params]]
icon = "brand-instagram"